package dev.kiser.controllers;

import com.auth0.jwt.interfaces.DecodedJWT;
import com.google.gson.Gson;
import dev.kiser.daos.EmployeeDaoPostgres;
import dev.kiser.daos.ExpenseDaoPostgres;
import dev.kiser.daos.ManagerDaoPostgres;
import dev.kiser.entities.Expense;
import dev.kiser.services.ExpenseService;
import dev.kiser.services.ExpenseServiceIF;
import dev.kiser.utils.JwtUtil;
import io.javalin.http.Handler;

import java.util.Set;

public class ExpenseController {

    private final ExpenseServiceIF expenseService = new ExpenseService(new ExpenseDaoPostgres(), new EmployeeDaoPostgres(), new ManagerDaoPostgres());

    /**
     * Get all expenses handler Determines whether to use employee or manager version for the query params Only manager
     * can get all expenses for all employees
     */
    public Handler getAllExpensesHandler = ctx -> {

        // get query params
        String eid = ctx.queryParam("eid", "NONE");
        String status = ctx.queryParam("status", "NONE");

        try {
            // check the jwt sent via authorization
            String jwt = ctx.queryParam("Authorization");
            DecodedJWT decodedJWT = JwtUtil.isValidJWT(jwt); // make sure it is valid

            // role must be manager
            if (decodedJWT.getClaim("role").asString().equals("manager")) {

                String expensesJSON = isManager(eid, status);
                // if nothing went wrong and null was not returned
                if (expensesJSON != null) {
                    ctx.result(expensesJSON);
                    ctx.status(200);

                } else {
                    // an error likely happened in the status since getAllExpenses works as long as the database exists
                    ctx.result("Please check your status value. Must be 'pending', 'approved', or 'denied'");
                    ctx.status(404);
                }

            } else {
                // role is employee
                String expensesJSON = isEmployee(eid, status);

                // checking if something went wrong
                if (expensesJSON == null) {
                    ctx.result("Please check your status value. Must be 'pending', 'approved', or 'denied'");
                    ctx.status(404);

                } else if (expensesJSON.equals("null eid")) {
                    // if the employee is was null, 'null eid' is returned
                    ctx.result("Employee ID is null");
                    ctx.status(404);

                } else {
                    ctx.result(expensesJSON);
                    ctx.status(200);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            ctx.status(403);
            ctx.result("Missing authorization or improper token");
        }
    };

    /**
     * Handles the case of the employee being a manager
     *
     * @param eid    employee id given by URI
     * @param status status given by URI
     *
     * @return the JSON string or null
     */
    private String isManager(String eid, String status) {
        Set<Expense> expenses;

        // get all expenses if query params do not exist
        if (eid.equals("NONE") || status.equals("NONE")) {
            expenses = this.expenseService.getAllExpenses();

        } else {
            // get all expenses for all employees
            // -1 is the value used since no id generated by the database is negative
            expenses = this.expenseService.getExpenseByStatus(-1, status);
        }

        // if nothing went wrong and null was not returned
        if (expenses != null) {
            // create and send the JSON
            Gson gson = new Gson();
            return gson.toJson(expenses);

        } else {
            return null;
        }
    }

    /**
     * Handles the case of the employee not being a manager
     *
     * @param eid    employee id given by URI
     * @param status status given by URI
     *
     * @return JSON string, null is in get expense methods, and 'null' eid for no eid given
     */
    private String isEmployee(String eid, String status) {
        Set<Expense> expenses;

        if (eid != null) {
            // get the employee id to get the expenses for
            int empId = Integer.parseInt(eid);

            // if the status is nothing, we are getting all the expenses for an employee
            if (status.equals("NONE")) {
                expenses = this.expenseService.getExpensesByEmployee(empId);

            } else {
                // otherwise get the expenses by status
                expenses = this.expenseService.getExpenseByStatus(empId, status);
            }

            // if nothing went wrong and null was not returned
            if (expenses != null) {
                Gson gson = new Gson();
                return gson.toJson(expenses);

            } else {
                return null;
            }
        } else {
            return "null eid";
        }
    }

}
