package dev.kiser.controllers;

import com.auth0.jwt.interfaces.DecodedJWT;
import com.google.gson.Gson;
import dev.kiser.daos.EmployeeDaoPostgres;
import dev.kiser.daos.ExpenseDaoPostgres;
import dev.kiser.daos.ManagerDaoPostgres;
import dev.kiser.entities.Expense;
import dev.kiser.services.ExpenseService;
import dev.kiser.services.ExpenseServiceIF;
import dev.kiser.utils.JwtUtil;
import io.javalin.http.Handler;
import org.apache.log4j.Logger;

import java.util.Set;

public class ExpenseController {

    private final ExpenseServiceIF expenseService = new ExpenseService(new ExpenseDaoPostgres(), new EmployeeDaoPostgres(), new ManagerDaoPostgres());
    public Handler createExpense = ctx -> {
        String body = ctx.body();
        Gson gson = new Gson();
        Expense expense = gson.fromJson(body, Expense.class);
        expenseService.registerExpense(expense.getEmpId(), expense);
        String json = gson.toJson(expense);
        ctx.result(json);
        ctx.status(201);
    };
    Logger logger = Logger.getLogger(ExpenseController.class);

    /**
     * Handles the case of the employee being a manager
     *
     * @param eid    employee id given by URI
     * @param status status given by URI
     *
     * @return the JSON string or null
     */
    private String isManager(String eid, String status) {
        Set<Expense> expenses;

        // get all expenses if query params do not exist
        if (eid.equals("NONE") || status.equals("NONE")) {
            expenses = this.expenseService.getAllExpenses();

        } else {
            // get all expenses for all employees
            // -1 is the value used since no id generated by the database is negative
            expenses = this.expenseService.getExpenseByStatus(-1, status);
        }

        // if nothing went wrong and null was not returned
        if (expenses != null) {
            // create and send the JSON
            Gson gson = new Gson();
            return gson.toJson(expenses);

        } else {
            return null;
        }
    }

    /**
     * Handles the case of the employee not being a manager
     *
     * @param eid    employee id given by URI
     * @param status status given by URI
     *
     * @return JSON string, null is in get expense methods, and 'null' eid for no eid given
     */
    private String isEmployee(String eid, String status) {
        Set<Expense> expenses;

        if (eid != null) {
            // get the employee id to get the expenses for
            int empId = Integer.parseInt(eid);

            // if the status is nothing, we are getting all the expenses for an employee
            if (status.equals("NONE")) {
                expenses = this.expenseService.getExpensesByEmployee(empId);

            } else {
                // otherwise get the expenses by status
                expenses = this.expenseService.getExpenseByStatus(empId, status);
            }

            // if nothing went wrong and null was not returned
            if (expenses != null) {
                Gson gson = new Gson();
                return gson.toJson(expenses);

            } else {
                return null;
            }
        } else {
            return "null eid";
        }
    }

    // end allExpenses controller and helpers
    //////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /**
     * Get all expenses handler Determines whether to use employee or manager version for the query params Only manager
     * can get all expenses for all employees
     */
    public Handler getAllExpensesHandler = ctx -> {

        // get query params
        String eid = ctx.queryParam("eid", "NONE");
        String status = ctx.queryParam("status", "NONE");

        try {
            // check the jwt sent via authorization
            String jwt = ctx.queryParam("Authorization");
            DecodedJWT decodedJWT = JwtUtil.isValidJWT(jwt); // make sure it is valid

            // role must be manager
            if (decodedJWT.getClaim("role").asString().equals("manager")) {

                // run the isManager section
                String expensesJSON = isManager(eid, status);

                // if nothing went wrong and null was not returned
                if (expensesJSON != null) {
                    ctx.result(expensesJSON);
                    ctx.status(200);

                } else {
                    // an error likely happened in the status since getAllExpenses works as long as the database exists
                    ctx.result("Please check your status value. Must be 'pending', 'approved', or 'denied'");
                    ctx.status(404);
                }

            } else {
                // role is employee
                // run the isEmployee section
                String expensesJSON = isEmployee(eid, status);

                // checking if something went wrong
                if (expensesJSON == null) {
                    ctx.result("Please check your status value. Must be 'pending', 'approved', or 'denied'");
                    ctx.status(404);

                } else if (expensesJSON.equals("null eid")) {
                    // if the employee is was null, 'null eid' is returned
                    ctx.result("Employee ID is null");
                    ctx.status(404);

                } else {
                    ctx.result(expensesJSON);
                    ctx.status(200);
                }
            }
        } catch (Exception e) {
            logger.error("Authorization error");
            ctx.status(403);
            ctx.result("Missing authorization or improper token");
        }
    };

    // end expense by id
    ////////////////////////////////////////////////////////////////////////////////////////////
    /**
     * Get the expense by id
     */
    public Handler getExpenseById = ctx -> {
        // get path params
        String exId = ctx.pathParam("xid");
        String empId = ctx.pathParam("eid");

        try {
            // make sure the values are integers
            int xid = Integer.parseInt(exId);
            int eid = Integer.parseInt(empId);

            // no error thrown, get the expense
            Expense expense = expenseService.getExpenseById(eid, xid);

            // if nothing went wrong with getting the expense
            if (expense == null) {
                ctx.result("Please check your ids to make sure they are valid");
                ctx.status(404);
            } else {
                Gson gson = new Gson();
                String expenseJSON = gson.toJson(expense);
                ctx.result(expenseJSON);
                ctx.status(200);
            }

        } catch (NumberFormatException e) {
            logger.error("The numerical values aren't numbers: " + exId + " : " + empId);
            ctx.result("The ids provided are not numbers");
            ctx.status(404);
        }
    };

    // end create expense
    //////////////////////////////////////////////////////////////////////////////////////////////


}
